### ISSUE TITLE
Import of ICS Files in the agenda of Firefox OS

### ISSUE THREAD

**Issue by Desiderius77** [Mozilla-Student-Projects/Projects-Tracker#65] opened 2013-11-05 10:29 UTC
Currently, the Agenda of Firefox OS only allows import of calendaring data through Google or CalDav servers. The objective of this project is to develop the importation of such data from local ICS files.

**Comment by ghost** [comment] 2014-01-20 13:45
My team project (M2 Miage Evry) is interested to do this project .

**Comment by Desiderius77** [comment] 2014-01-20 14:32
Give the names of all people in your team , add the link to your Github project and have fun :)

**Comment by ghost** [comment] 2014-01-20 14:46
team work : tjoker, Boss2509 and maybe another one guy but not sure . I update this list in few days .

**Comment by ghost** [comment] 2014-01-27 13:36
My final team work is :
- Boss2509
- tjoker
- JJamesR

We are ready to work on this project,  if you have any advice we take it . 

We start reading : 
- ICalendar Format
- Firefox os simulator 
- RFC 2445 
- Mozilla Lightning  / Sunbird

**Comment by Desiderius77** [comment] 2014-01-27 13:39
OK ! Just put your Github repo here !

Have also a look at the code of Agenda in Gaia !

**Comment by ghost** [comment] 2014-01-28 09:34
The repo : https://github.com/tjoker/ICSFile 

Have you some links for the code ? 
There is some docs too ?

**Comment by Yoric** [comment] 2014-01-28 10:22
Since you are modifying the code of the Gaia Agenda, you will actually need to fork [gaia](https://github.com/mozilla-b2g/gaia/). For more instructions, see [Hacking Gaia](https://wiki.mozilla.org/Gaia/Hacking).

**Comment by ghost** [comment] 2014-04-15 09:42
Hi , i have some problems to test my " gaia calendar apps" in firefox:
- For now i fork gaia in my repo and clone it on my computer.
  -I downloaded B2G clients 
  -I downloaded firefox os simulator 

But what ever i try i can't create the "profile" when they said "debug=1 make" , on windows 7 .

The command "make" doesn't exist on windows 7, so i dowlnand "MinGW" and few packages .. but after all it doesn't work very well the  directory "profile" is creating but it's empty . And there are lot of bugs around but i don't know why. 

On the Firefox OS simulator  there are few parameters :
- custom gaia profil directory : for now i don't have any 
- custom  runtime executable : i have b2g exe (path)

I have only one appliccation in firefox os simulator the " gaia calendar apps" , but when i tried to start firefox os simulator, to see my applicaiton  i had this error :

 "connecting to localhost:50142
11:23:08: connection timeout. Possible causes: didn't click on 'accept' (prompt).
11:23:08: disconnecting

**Comment by julienw** [comment] 2014-04-15 12:11
To build on Windows, you should install MozillaBuild, see https://wiki.mozilla.org/MozillaBuild

This will provide you the same environment we use to build on Windows. That said, we don't develop on Windows on day to day so there might be small issues. If you want to be sure that you'll have no issue, you can use a virtual machine with Linux. By chance, @ttaubert created ready-to-use virtual machines: http://timtaubert.de/blog/2014/04/a-ready-to-use-virtual-build-environment-for-firefox/ that you can probably use for Gaia as well. (Tim can complete if necessary)

About the other error: the way it works is that you must first run the simulator, and then connect to the simulator using the app manager. I don't exactly understand what you did so if you can be more precise I can try to help :)

Thanks !

**Comment by ghost** [comment] 2014-04-15 13:22
First ,thanks a lot for the replay . What i am trying to do is start gaia (previously downloaded)  throw firefox ( on windows 7) but for now i  have failed . I will try your solution and come back to you to inform you it's a  success or not . 
Thanks.

**Comment by ghost** [comment] 2014-04-19 12:15
Hi, after few research, i will try for the vm it's seems more appropriate, but it's take a while ... 
And about the other error, i did as you said : 

1) start the simulator
2) search your app with the app manager and push the update bouton
3) then The app calendar is on the simulator
4) but when i try to run it , i have a black screen and nothing happen ...
Is it connected to gaia profiles" ? ( because on windows 7, i didn't made it)

**Comment by julienw** [comment] 2014-04-19 14:14
In the app manager, you can then "debug" your app, once it's launched.

Can you have a look to the "console" tab in the app manager and see if there is anything meaningful?

**Comment by ghost** [comment] 2014-04-19 14:47
logs when i installed the app : 

16:35:33: Found simulator: Firefox OS 1.3
16:35:34: Starting simulator...
16:35:34: Simulator ready. Connecting.
16:35:34: connecting to localhost:49258
16:35:43: connected
16:35:43: Connected to simulator.
16:36:00: Installing the Calendar app...
16:36:03: Install completed.

in the debug section i found nothing . But when i look the app i have two warnings : 

the first one said that picture size is not correct 
the second one  said that certified app are  not fully supported by the application manager.

**Comment by ghost** [comment] 2014-04-19 14:49
when i look for  other app it's the same problem ...

**Comment by ghost** [comment] 2014-04-19 14:55
gaia profile is needed for this too ?  here is a picture when i try to start my app
![sans titre](https://cloud.githubusercontent.com/assets/6142761/2748726/ad197332-c7d2-11e3-9733-544f725a1516.png)

**Comment by ghost** [comment] 2014-04-20 08:25
Hey i found the mistakes but not all : 

First i fixed the 2 warnings ( it' was nothing but anyway it's done)
After, i looked the index.html ( the launch file which is in the manifest file) and there are outside references  of directory calendar app .

In the index.html :
script   defer src="/shared/js/l10n.js"    script
....
....
=>  nothing is found, it's why i had black screen.

But if i move the repesitory  "gaia/shared" at "gaia/app/calendar/shared" the application start well. 

But something is still wrong with file path because the app doesn't work fully   .
For example i can't save event, i have no account ...  

Do you know the problem on windows 7 ? maybe there are some configuration to do ?

**Comment by julienw** [comment] 2014-04-20 13:17
I somehow missed the fact that you were working on a app from Gaia.

This does not work so well with the app manager because we do some things at build time, it's not just a bunch of js/css/html files.

The best would be to use a standalone b2g but I don't know if it's possible to connect to it using the app manager then (and the app manager is what makes it easy to use the remote debugger and remote inspector).

You can download a standalone b2g on http://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-central/, you can choose the correct archive. From the gaia directory, `make b2g` probably does this automatically, but I'm not sure for Windows.

Then you can build a debug profile from the gaia directory:

``` bash
DEBUG=1 DESKTOP=0 NO_LOCK_SCREEN=1 PROFILE_FOLDER=profile-b2g make
```

This will generate a debug profile in the directory `profile-b2g`. What's nice with a debug profile is that your changes in apps/calendar will be automatically picked up when you reload the app in b2g, no need to push the app.

Then you can launch your downloaded b2g with this profile:

``` bash
./b2g/b2g-bin -profile <path to profile-b2g>
```

Another possibility is to run Gaia in Firefox; the problem is that it has subtle bugs, but it can work well enough for you. You can do this:

``` bash
PROFILE_FOLDER=profile-browser DEBUG=1 DESKTOP=1 make
```

and then run firefox using this profile: `<path to firefox>/firefox --no-remote -profile <path to profile-browser>`.

Same thing here: since it's a debug profile, changes to `app/calendar` are picked up.

Hope this helps...

**Comment by ghost** [comment] 2014-04-20 13:46
thank a lot ,it's will be very usefull  when we test it  on a firefox phone .

In searching i found this solution ,  it's almost the same that one of yours : 

1) Download a standalone b2g 
2) pickup the calendar directory
3) move on app manager
4) start the os simulator and update the app

Then the application is fully operationel, thank any way .

Now i try to run my own app , but i have some issues : 

I need to upload a file but i can't found it  :
Maybe i need to push a file in the ' SD CARD' and chose a specific directory , how i can do this ? I look arround datauri to simulate a file ....

On the first picture you will see :

app in firefox => all is ok
app in firefox OS  => when i push "grey bouton" i have black screen and a loading progression bar
![sans titre](https://cloud.githubusercontent.com/assets/6142761/2750645/148c0c4a-c892-11e3-9b8f-adb2b4244aad.png)

The second picture, show you the "search file menu" when i push on "LOAD ICS FILE" :

![sans titre2](https://cloud.githubusercontent.com/assets/6142761/2750647/1985074c-c892-11e3-853e-54f2e52f9ec1.png)

**Comment by julienw** [comment] 2014-04-20 21:22
I don't really know how to implement a file selector. Usually we use DeviceStorage. Maybe an activity would work too. But you should really ask the calendar maintainers, I'm not one of them :)

**Comment by ghost** [comment] 2014-04-21 07:30
OK , i will do it but where i can found a calendar maintainer ? 
( if you know one of them, this will be awesome ) .
There is a mozilla website dedicated to the firefox app maintenance ?

This is my first contribution to the OS firefox, I'm not used to working like that , I apologize for my "neophism"....
Thanks :) .

**Comment by jdm** [comment] 2014-04-21 08:21
https://wiki.mozilla.org/Modules/FirefoxOS#Calendar

**Comment by AntoineTurmel** [comment] 2017-02-17 16:09
Closing it for now as Firefox OS is discontinued...

**Closed as completed by AntoineTurmel** 2017-02-17 16:09 UTC
Labels: JavaScript, B2G, low
